# Generated by Django 2.1.15 on 2025-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование партнера')),
                ('position', models.CharField(default='Директор', max_length=50, verbose_name='Директор')),
                ('phone', models.CharField(default='+7 223 322 22 32', max_length=20, verbose_name='Телефон')),
                ('rating', models.IntegerField(default=10, verbose_name='Рейтинг')),
                ('partner_type', models.CharField(default='10%', max_length=50, verbose_name='Тип')),
            ],
        ),
    ]
